import type { Conversation, ProfileExtended, User } from "./types";

export const CURRENT_USER: ProfileExtended = {
  id: "me",
  name: "Chibuzor",
  location: "Morgantown, WV, USA",
  avatarUrl: "https://picsum.photos/id/338/600/600",
  coverUrl: "https://picsum.photos/id/193/1200/400",
  verification: {
    payment: true,
    phone: true,
    governmentId: false,
    address: "pending",
  },
  status: "wants_to_meet_up",
  referencesCount: 4,
  friendsCount: 29,
  languages: ["English", "French", "Russian"],
  occupation: "Chemical Engineer",
  education: "BS in Chemical Engineering",
  interests: [
    "Hiking",
    "Guitar",
    "Travel",
    "Engineering",
    "Cooking",
    "Language Exchange",
  ],
  age: 31,
  gender: "Male",
  joinedDate: "2014",
  responseRate: 100,
  responseTime: "Replies within an hour",
  lastLogin: "Today",
  aboutMe:
    "I love playing music and I've been playing guitar for almost 2 years. I love to do the outdoors stuff e.g. hiking, biking, etc. I'm a chill dude who can get down with hanging out or partying at the clubs. It just depends on the night!\n\nAlso, I'm not gay. No homo.",
  whyImOnCouchsurfing:
    "I am a recent engineering graduate looking for awesome people to travel the world with!",
  oneAmazingThing: "I've backpacked through 15 countries in 3 months.",
  teachLearnShare:
    "I can teach you guitar basics, some engineering concepts, or we can share travel stories.",
  musicMoviesBooks:
    "Music - Country, Ed Sheeran, Literally anything on acoustic guitar.\nMovies - High School Musicals 1-3 (don't judge).",
  countriesVisited: [
    "Germany",
    "France",
    "Estonia",
    "United States",
    "Canada",
    "Hungary",
    "Poland",
    "England",
  ],
  countriesLived: ["United States", "Nigeria"],
  homeDetails: {
    maxGuests: 1,
    lastMinute: true,
    preferredGender: "Any",
    kidFriendly: false,
    petFriendly: false,
    smokingAllowed: false,
    hasPets: false,
    hasChildren: false,
    sleepingArrangements: "Shared room",
    roommateSituation: "I live with 2 roommates who are also students.",
    publicTransport: "Bus stop is 5 mins away.",
    wheelchairAccessible: false,
  },
  photos: [
    "https://picsum.photos/id/1011/600/400",
    "https://picsum.photos/id/1012/600/400",
    "https://picsum.photos/id/1013/600/400",
    "https://picsum.photos/id/1014/600/400",
  ],
  references: [
    {
      id: "ref1",
      authorName: "Renzo Diaz",
      authorAvatar: "https://picsum.photos/id/55/100/100",
      authorLocation: "New York, USA",
      type: "Personal",
      date: "Aug 2024",
      text: "Chibuzor is the life of the party! We hiked together and he played guitar by the fire. Awesome dude.",
      isPositive: true,
    },
    {
      id: "ref2",
      authorName: "Sarah Jenkins",
      authorAvatar: "https://picsum.photos/id/65/100/100",
      authorLocation: "London, UK",
      type: "Host",
      date: "May 2023",
      text: "Very clean and respectful guest. Would host again!",
      isPositive: true,
    },
  ],
};

// Generate Mock Users for Dashboard
const generateMockUsers = (count: number): User[] => {
  const statuses: User["status"][] = [
    "accepting_guests",
    "maybe_accepting_guests",
    "not_accepting_guests",
    "wants_to_meet_up",
  ];
  const responseTimes = [
    "Replies within an hour",
    "Replies within a day",
    "Replies in 1-3 days",
    "Takes a week or more",
  ];
  const interestsList = [
    "Hiking",
    "Photography",
    "Cooking",
    "Yoga",
    "Surfing",
    "Coding",
    "Music",
    "Art",
    "History",
    "Foodie",
  ];
  const educations = [
    "Bachelors in Arts",
    "Masters in Science",
    "PhD in Physics",
    "Self-taught",
    "University of Life",
  ];

  return Array.from({ length: count }).map((_, i) => ({
    id: `user-${i}`,
    name:
      [
        "Abner Bogan",
        "Avi Amon",
        "J.R. Hamilton",
        "Natalie Lorenze",
        "Kristen Selin",
        "Cole Weaver",
        "Karima Neghmouche",
      ][i % 7] + (i > 6 ? ` ${i}` : ""),
    location: [
      "Morgantown, WV",
      "New York, NY",
      "Pittsburgh, PA",
      "Washington, DC",
      "Columbus, OH",
    ][i % 5],
    avatarUrl: `https://picsum.photos/id/${150 + i}/200/200`,
    coverUrl: `https://picsum.photos/id/${250 + i}/600/200`,
    verification: {
      payment: i % 3 === 0,
      phone: i % 2 === 0,
      governmentId: i % 4 === 0,
      address: i % 5 === 0 ? "verified" : "unverified",
    },
    status: statuses[i % 4],
    referencesCount: Math.floor(Math.random() * 50),
    friendsCount: Math.floor(Math.random() * 200),
    languages: ["English", i % 2 === 0 ? "Spanish" : "French"],
    occupation: ["Student", "Engineer", "Artist", "Teacher", "Nomad"][i % 5],
    education: educations[i % 5],
    interests: [
      interestsList[i % 10],
      interestsList[(i + 1) % 10],
      interestsList[(i + 3) % 10],
    ],
    age: 20 + Math.floor(Math.random() * 20),
    gender: i % 2 === 0 ? "Female" : "Male",
    joinedDate: (2015 + Math.floor(Math.random() * 8)).toString(),
    responseRate: 50 + Math.floor(Math.random() * 50),
    responseTime: responseTimes[i % 4],
    lastLogin: ["Today", "Yesterday", "Last Week"][i % 3],
  }));
};

export const MOCK_USERS = generateMockUsers(16);

export const MOCK_INBOX: Conversation[] = [
  {
    id: "conv1",
    otherUser: {
      id: "seany",
      name: "SEANY KANE",
      avatarUrl: "https://picsum.photos/id/1062/100/100",
      location: "Indonesia, Bali",
      verification: {
        payment: true,
        phone: true,
        governmentId: true,
        address: "verified",
      },
      referencesCount: 125,
      friendsCount: 580,
      languages: ["English"],
      occupation: "Digital Nomad",
      education: "Life University",
      interests: ["Surfing", "Digital Nomad", "Crypto"],
      age: 39,
      gender: "Male",
      joinedDate: "2015",
      responseRate: 80,
      responseTime: "Replies within a day",
      lastLogin: "yesterday",
      status: "accepting_guests",
    },
    lastMessage: "Brother are you there??",
    lastMessageDate: "2y ago",
    status: "active",
    requestType: "meetup",
    isRequest: false,
    messages: [
      {
        id: "m1",
        senderId: "seany",
        text: "Hey man, saw you were in Bali!",
        timestamp: "2023-01-15T10:00:00Z",
        isRead: true,
      },
      {
        id: "m2",
        senderId: "me",
        text: "Yeah just arrived!",
        timestamp: "2023-01-15T10:05:00Z",
        isRead: true,
      },
      {
        id: "m3",
        senderId: "seany",
        text: "Brother are you there??",
        timestamp: "2023-01-16T09:00:00Z",
        isRead: false,
      },
    ],
  },
  {
    id: "conv2",
    otherUser: {
      id: "vlad",
      name: "Vlad Vee",
      avatarUrl: "https://picsum.photos/id/1005/100/100",
      location: "Moscow, Russia",
      verification: {
        payment: false,
        phone: false,
        governmentId: false,
        address: "unverified",
      },
      referencesCount: 12,
      friendsCount: 5,
      languages: ["Russian", "English"],
      occupation: "Student",
      education: "Moscow State",
      interests: ["Coding", "Vodka", "Chess"],
      age: 24,
      gender: "Male",
      joinedDate: "2020",
      responseRate: 60,
      responseTime: "Replies in 1-3 days",
      lastLogin: "1 week ago",
      status: "maybe_accepting_guests",
    },
    lastMessage: "Ciao! You're welcome ;)",
    lastMessageDate: "7y ago",
    status: "active",
    requestType: "host",
    isRequest: false,
    messages: [
      {
        id: "m1",
        senderId: "vlad",
        text: "Can I stay at your place?",
        timestamp: "2017-05-10T10:00:00Z",
        isRead: true,
      },
      {
        id: "m2",
        senderId: "me",
        text: "Sure thing, accepted.",
        timestamp: "2017-05-10T12:00:00Z",
        isRead: true,
      },
      {
        id: "m3",
        senderId: "vlad",
        text: "Ciao! You're welcome ;)",
        timestamp: "2017-05-12T09:00:00Z",
        isRead: true,
      },
    ],
  },
  {
    id: "conv3",
    otherUser: {
      id: "new_friend",
      name: "Elara Moon",
      avatarUrl: "https://picsum.photos/id/334/100/100",
      location: "Portland, OR",
      verification: {
        payment: true,
        phone: true,
        governmentId: false,
        address: "verified",
      },
      referencesCount: 8,
      friendsCount: 42,
      languages: ["English", "German"],
      occupation: "Artist",
      education: "Art School",
      interests: ["Painting", "Hiking", "Veganism"],
      age: 27,
      gender: "Female",
      joinedDate: "2022",
      responseRate: 95,
      responseTime: "Replies within an hour",
      lastLogin: "Today",
      status: "wants_to_meet_up",
    },
    lastMessage: "Hey! I noticed we both like hiking. Want to grab coffee?",
    lastMessageDate: "10m ago",
    status: "active",
    requestType: "meetup",
    isRequest: true,
    messages: [
      {
        id: "m1",
        senderId: "new_friend",
        text: "Hey! I noticed we both like hiking. I'm passing through Morgantown next week. Want to grab coffee or go for a trail run?",
        timestamp: new Date().toISOString(),
        isRead: false,
      },
    ],
  },
  {
    id: "conv4",
    otherUser: {
      id: "archived_user",
      name: "Old Host",
      avatarUrl: "https://picsum.photos/id/34/100/100",
      location: "Paris, France",
      verification: {
        payment: true,
        phone: false,
        governmentId: false,
        address: "unverified",
      },
      referencesCount: 50,
      friendsCount: 100,
      languages: ["French", "English"],
      occupation: "Baker",
      education: "Culinary Institute",
      interests: ["Baking", "History", "Wine"],
      age: 45,
      gender: "Male",
      joinedDate: "2010",
      responseRate: 90,
      responseTime: "Replies within a day",
      lastLogin: "Last Month",
      status: "not_accepting_guests",
    },
    lastMessage: "Hope you enjoyed Paris!",
    lastMessageDate: "5y ago",
    status: "archived",
    requestType: "host",
    messages: [
      {
        id: "m1",
        senderId: "archived_user",
        text: "Hope you enjoyed Paris!",
        timestamp: "2019-06-01T12:00:00Z",
        isRead: true,
      },
    ],
  },
];

export const AI_RESPONSES = [
  "That sounds awesome! Tell me more about it.",
  "Haha, totally agree with you there.",
  "I'm actually planning a trip soon, maybe we can cross paths!",
  "Wow, that's really interesting.",
  "Sure thing!",
  "Let me check my schedule and get back to you.",
  "Cheers from my side of the world!",
  "Have you ever been to Thailand? I loved it there.",
  "Nice to meet you virtually!",
];

export const getRandomResponse = () =>
  AI_RESPONSES[Math.floor(Math.random() * AI_RESPONSES.length)];
